### DISCUSSION TITLE
Customizing action item labels

### DISCUSSION THREAD

**Discussion by giuseb** [activeadmin/activeadmin#8610] [Help] [answered]
I would like to customize the edit and delete button labels on the show page.
For example, instead of "Edit article", I would prefer to see "Edit", possibly accompanied by an icon.
Is this feasible?

**Comment by aalyahya** [comment, marked as answer]
You can override the translation. Default localization is: 

```yaml
en:
  active_admin:
    new_model: "New %{model}"
    edit_model: "Edit %{model}"
    delete_model: "Delete %{model}"
```

You can do:
```yaml
en:
  active_admin:
    new_model: "New +"
    edit_model: "Edit"
    delete_model: "Delete ⛌"
```
