### DISCUSSION TITLE
Feature: Tailwind 4 compatibility

### DISCUSSION THREAD

**Discussion by henrikbjorn** [activeadmin/activeadmin#8621] [General]
Pre-requirements:
- [ ] https://github.com/rails/cssbundling-rails/pull/164

---

### Expected behavior

Tailwind 4 goes a long way of having BC with earlier versions. But the `plugin.js` is using some invalid utility types and there for isn't compatible with it.

### Actual behavior

Should work with Tailwind 4 through the `@plugin` directlive or their js config bc layer

### How to reproduce

Install ActiveAdmin and use Tailwind 4

**Comment by tagliala** [comment]
Hello,

this is a feature request to migrate to Tailwind 4

**Comment by henrikbjorn** [comment]
``` css
@import "tailwindcss" source(none);

@plugin "@activeadmin/activeadmin/plugin";

@source "/bundle/ruby/3.4.0/gems/activeadmin-4.0.0.beta15/app/views/**/*.{arb,erb,html,rb}";
@source "/bundle/ruby/3.4.0/gems/activeadmin-4.0.0.beta15/plugin.js";
@source "/app/node_modules/flowbite/plugin.js";

@source "../../admin/**/*.rb";
@source "../../views/active_admin/**/*.{arb,erb,html,rb}";
@source "../../views/admin/**/*.{arb,erb,html,rb}";

@custom-variant dark (&:where(.dark, .dark *));

@utility ring-opacity-5 {
  --tw-ring-opacity: 0.05;
}

@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--color-gray-200, currentColor);
  }
}
```

This works for Tailwind 4
