### ISSUE TITLE
Can't translate model name in has_many

### ISSUE THREAD

**Issue by marcusvmsa** [activeadmin/activeadmin#1109]
I have created two models, `Category` and `Pic`, where Category has many Pics...
On the form:

```
  form :html => { :multipart => true } do |f|
   f.inputs "Album" do
     f.input :name    
   end

   f.inputs "Imagens" do
     f.has_many :pics do |p|
       p.input :file, :as => :file, :label => "Imagem", :hint => p.object.file.nil? ? p.template.content_tag(:span, "Nenhumca imagem cadastrada") : p.template.image_tag(p.object.file.url(:thumb))
       p.input :_destroy, :as=>:boolean, :required => false, :label => 'Deletar imagem'
     end 
   end
```

My problem is, the button to add a new Pic is translated at half... in pt-BR.yml i have:

```
  activerecord:
    models:
      pic: 
        one: "Foto"  
        other: "Fotos" 
  active_admin:
    has_many_new: "Adicionar Novo(a) %{model}"
```

I want the button text be Adicionar Novo(a) Foto instead Adicionar Novo(a) Pic
