### ISSUE TITLE
Boolean fields style is too large

### ISSUE THREAD

**Issue by simonc** [activeadmin/activeadmin#1275]
When you have a boolean field the style is the following:

``` css
li.boolean label {
  width: 100%;
  padding-left:20%; 
  padding-right: 10px; 
  text-transform: none !important;
  font-weight: normal;
}
```

The problem is that `width` and `padding` make the field larger than 100% of its parent and you end up with a big white space at the right of the page.

Setting `width: 80%` fixes the issue.
