### ISSUE TITLE
Add flash messages for actions 

### ISSUE THREAD

**Issue by jefferson** [activeadmin/activeadmin#1421]
Add messages in locale for translate a simple notice and alert, example:

``` yaml
Any-language
flash:
    actions:
      create:
        notice: '%{resource_name} was successfully created.'
        alert: '%{resource_name} could not be created.'
      update:
        notice: '%{resource_name} was successfully updated.'
        alert: '%{resource_name} could not be updated.'
      destroy:
        notice: '%{resource_name} was successfully destroyed.'
        alert: '%{resource_name} could not be destroyed.'
```
