### ISSUE TITLE
I18n: native Formatastic I18n labels are used in some cases

### ISSUE THREAD

**Issue by johnnyshields** [activeadmin/activeadmin#1724]
I'm not sure whether or not this is by design but just wanted to raise in case anyone else encounters it.

It seems in some cases that the native labels of Formtastic are used instead of overrides from ActiveAdmin, for example, "Create Model" button on "new" page.

I found that this has no meaning:

``` yaml
# /config/locals/en.yml
en:
  active_admin:
    create_model: "Create %{model}"
```

and instead i must do this:

``` yaml
# /config/locals/en.yml
en:
  formtastic:
    create: "Create %{model}"
```

If this is by design, maybe it's a good idea to add it to the documentation?
