### ISSUE TITLE
4 steps to add auto complete in ActiveAdmin

### ISSUE THREAD

**Issue by rainchen** [activeadmin/activeadmin#1754]
Actually this is not an issue, but a tips for ActiveAdmin users which need autocomplete functional.
OK here we go.

Take adding autocomple for email column of admin_user model as an example.
1. add gem "rails3-jquery-autocomplete"
2. set reqruied js in app/assets/javascripts/active_admin.js:

``` js
//= require autocomplete-rails
```
1. add autocomplete routes and action in app/admin/admin_user.rb (for example):
   
   ``` ruby
   # define routes for "autocomplete :admin_user, :email"
   collection_action :autocomplete_admin_user_email, :method => :get
   
   controller do
       autocomplete :admin_user, :email
   end
   ```
2. set input as :autocomplete type and url for ajax

``` ruby
f.input :email, :as => :autocomplete, :url => autocomplete_admin_user_email_admin_admin_users_path
```

How to apply autocomplete for "filter"?

``` ruby
# make "filter :email" can autocomplete
filter :email_contains, :as => :autocomplete, :url => '/admin/admin_users/autocomplete_admin_user_email',
                        :label => "Search Email", :required => false,
                        :wrapper_html => { :style => "list-style: none" }
```

**Comment by sbpipb** [comment]
Hi @whatcould ,

 You are definitely right, I've encountered that same problem now.

Completed 500 Internal Server Error in 49ms

    ActionView::Template::Error (Unable to find input class FilterAutocompleteInput):
        1: insert_tag renderer_for(:index)

I tried reading your advice over and over, but I'm kinda confused on where I should paste that code snippet. Should I create a new "config/initializers/" for autocomplete or should I just paste it under the Active Admin(config/initializers/active_admin.rb) initializer?   Rails newbie here

**Comment by sbpipb** [comment]
@whatcould I did the instructions you gave. But i've encountered a js issue.
    
    TypeError: t(...).autocomplete is not a function

Did I miss anything?

**Comment by moofmayeda** [comment]
I get the missing template error when the `autocomplete :tag, :name` part is in the wrong controller. I believe if you put it in the controller of the resource that's being queried (which is not necessarily the same controller as the one that's handling the form), that'll fix the template error.

**Comment by whatcould** [comment]
Here's an updated version of the previous code block, for AA 1.0.0.pre1, to add an autocomplete type to AA filters. For Rails 4 I'm using the 'rails-jquery-autocomplete' gem (https://github.com/crowdint/rails3-jquery-autocomplete).

```ruby
# For autocomplete filters
module ActiveAdmin
  module Inputs
    class FilterAutocompleteInput < ::Formtastic::Inputs::AutocompleteInput
      include ActiveAdmin::Inputs::Filters::Base

      def input_name
        "#{super}_eq"
      end

      def extra_input_html_options
        {}
      end
    end
  end
end
```

**Comment by mikelarkin** [comment]
Solution to a few of the issues (templates missing, JS conflict, $().autocomplete missing)

## Stack ##
Rails 4.2.1
ActiveAdmin 1.0.0.pre1 0b4b228

### Gemfile ###
```
gem 'jquery-rails'
gem 'rails-jquery-autocomplete' # This is the maintained version of rails3-jquery-autocomplete
```

### active_admin.js.coffee ###

```coffee
#= require active_admin/base
#= require jquery-ui/autocomplete
```

In my case, I have an Order model that belongs_to a Partner.  So, I want to autocomplete order.partner_id

### admin/partner.rb ###

```ruby
  collection_action :autocomplete_partner_name, :method => :get

  controller do
    autocomplete :partner, :name, :full => true
  end
```

### admin/order.rb ###

In my form I have:

```ruby
f.input :partner_name, :as => :autocomplete, 
        :url => autocomplete_partner_name_admin_partners_path, 
        :input_html => {:id_element => '#order_partner_id','data-auto-focus' => true}

f.input :partner_id, :as => :hidden
```

### models/order.rb ###

I needed to be able to pull the Partner#name field when editing an order,
so I made an accessor / memoized getter/setter

```ruby
  attr_accessor :partner_name # for autocomplete
  def partner_name
    @partner_name ||= self.try(:partner).try(:name)
    return @partner_name
  end
```

### stylesheets/active_admin.css.scss ###

The CSS gets messed up too, so I pasted in the bootstrap overrides and matched 
the DOM classes

```css
.ui-autocomplete {
    position: absolute;
    top: 100%;
    left: 0;
    z-index: 1000;
    float: left;
    display: none;
    min-width: 160px;
    padding: 4px 0;
    margin: 0 0 10px 25px;
    list-style: none;
    background-color: #ffffff;
    border-color: #ccc;
    border-color: rgba(0, 0, 0, 0.2);
    border-style: solid;
    border-width: 1px;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    border-radius: 5px;
    -webkit-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
    -moz-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
    box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
    -webkit-background-clip: padding-box;
    -moz-background-clip: padding;
    background-clip: padding-box;
    *border-right-width: 2px;
    *border-bottom-width: 2px;
}

.ui-menu-item > a.ui-corner-all {
    display: block;
    padding: 3px 15px;
    clear: both;
    font-weight: normal;
    line-height: 18px;
    color: #555555;
    white-space: nowrap;
    text-decoration: none;
}

.ui-state-hover, .ui-state-focus {
    color: #fff;
    text-decoration: none;
    background-color: #3db1ff;
    border-radius: 0px;
    -webkit-border-radius: 0px;
    -moz-border-radius: 0px;
    background-image: none;
}
```
