### ISSUE TITLE
I18n: model names and attributes

### ISSUE THREAD

**Issue by jassa** [activeadmin/activeadmin#1792]
ActiveAdmin translates items in the menu ok, but I can't get it to translate column names and attributes automatically in the rest of the page (e.g. columns, filters, etc).

Solutions mentioned in closed issues involve using something like: `column I18n.t(:description) do { ... }`
I don't think that's an optimal solution though.

Please let me know if there's already a better way to do this, otherwise I might give it a shot this weekend.

**Comment by giovannibenussi** [comment]
In case someones miss it, when using internationalization, you also need to include your current language at the begginning of the translations file (in this case 'es'):

```
es:
  activerecord: 
    models: 
      user: 
        one: "Usuario" 
        other: "Usuarios"
    attributes:
      user:
        first_name: "Nombres"
```
