### ISSUE TITLE
`resource_name` and `plural_resource_name` do not play well with i18n

### ISSUE THREAD

**Issue by knoopx** [activeadmin/activeadmin#202]
A locale file with:

```
es: 
  activerecord: 
        models:
          list:
            one: Clasificación
            other: Clasificaciones
```

return the following:

```
resource_name # Clasificación
plural_resource_name # Clasificacións
```

`plural_resource_name` implementation should use:

```
resource.model_name.human(:count => 2)  
```
