### ISSUE TITLE
Labels for search filters should be translatable per search field

### ISSUE THREAD

**Issue by grzegorzblaszczyk** [activeadmin/activeadmin#2160]
Scenario: 

In slavic languages like Polish, Czech, Slovak, Russian but also in other languages like Finnish you have different forms of nouns.

For example: 

PL: "Szukaj nazwy" => EN: "Search name"
PL: "Szukaj opisu" => EN: "Search description"

but: 
PL: "Nazwa" => EN: "Name"
PL: "Opis" => EN: "Description"

With new keys like:

``` yml
pl: 
  active_admin:
    search_field:
      name: "Szukaj nazwy"
      description: "Szukaj opisu"
```

it can be done pretty easily. 

Of course search field named 'description' should be translated the same across all models because this is the same type of data.
