### ISSUE TITLE
i18n active admin not picking my activerecord translation

### ISSUE THREAD

**Issue by Phazz** [activeadmin/activeadmin#2174]
Hi there,

My eyes are tired reading all the issues related to i18n, still I did not find a fix for my issue.

I have translation working great for active admin and decided to translate my resource and attributes.

In my es.yml I have :

```
es:
  activerecord:
    adminuser: "Usuario"

  active_admin:
    dashboard: "Inicio"
...
```

Why Active Admin picks active_admin translation but not active record ?

Rails 3.2.13
Active Admin 0.6.0

Thanks in advance,
