### ISSUE TITLE
datepicker dateformat not working

### ISSUE THREAD

**Issue by martinezpenya** [activeadmin/activeadmin#2285]
In my `/config/locales/i18n.ca.yml` I have:

```
ca:
  date:
    abbr_day_names:
    - Dg
    - Dl
    - Dm
    - Dc
    - Dj
    - Dv
    - Ds
    abbr_month_names:
    - ~,
    - Gen
    - Feb
    - Mar
    - Abr
    - Mai
    - Jun
    - Jul
    - Ago
    - Set
    - Oct
    - Nov
    - Des
    day_names:
    - Diumenge
    - Dilluns
    - Dimarts
    - Dimecres
    - Dijous
    - Divendres
    - Dissabte
    formats:
      default: ! '%d-%m-%Y'
      long: ! '%d de %B de %Y'
      short: ! '%d de %b'
```

But once datepicker is showed up and I picked a date is showed as 'yyyy-mm-dd'
