### ISSUE TITLE
Unwanted style applied to index columns

### ISSUE THREAD

**Issue by TimPetricola** [activeadmin/activeadmin#2531]
If a column is named `highlight` and is displayed on the index, the column will be displayed in yellow.
![Screenshot](https://f.cloud.github.com/assets/674084/1262515/f0a64f64-2c3f-11e3-87b0-20e4875713e7.jpg)

It's caused by the cell having a `.highlight`class.
![DOM](https://f.cloud.github.com/assets/674084/1262516/f0a6f70c-2c3f-11e3-8e7a-136b996825ff.jpg)

A similar issue would appear for `small`, `large`, `hide` (even worse), `quiet`, `loud`, `added` and `removed` columns. (and useless overwritten css for `first`, `last`, `top`, `bottom`).

The cause is the following CSS helper classes at the end of `/app/assets/stylesheets/active_admin/_typography.css.scss`

``` css
// Helper Classes
.small      { font-size: .8em; margin-bottom: 1.875em; line-height: 1.875em; }
.large      { font-size: 1.2em; line-height: 2.5em; margin-bottom: 1.25em; }
.hide       { display: none; }

.quiet      { color: #666; }
.loud       { color: #000; }
.highlight  { background:#ff0; }
.added      { background:#060; color: #fff; }
.removed    { background:#900; color: #fff; }

.first      { margin-left:0; padding-left:0; }
.last       { margin-right:0; padding-right:0; }
.top        { margin-top:0; padding-top:0; }
.bottom     { margin-bottom:0; padding-bottom:0; }
```

What could be a workaround for that? Maybe applying a `model_column` class instead of just `column` on cells? (e.g. `artist_highlight` instead of `highlight`).
