### ISSUE TITLE
Incorrect translation to batch_actions destroy in pt-BR and pt-PT

### ISSUE THREAD

**Issue by brunojabs** [activeadmin/activeadmin#2942]
``` yml
  # config/locales/pt-BR.yml
  batch_actions:
    labels:
      destroy: "Excluído" # should be "Excluir"
```
