### ISSUE TITLE
Rails 4.2 still complains about deprecated ActiveRecord #column_for_attribute

### ISSUE THREAD

**Issue by rdj** [activeadmin/activeadmin#3838]
Active Admin produces a deprecation warning with Rails 4.2.1.rc3:

```DEPRECATION WARNING: `#column_for_attribute` will return a null object for non-existent columns in Rails 5. Use `#has_attribute?` if you need to check for an attribute's existence. (called from is_boolean? at /var/jenkins/.rvm/gems/ruby-2.2.1@project/bundler/gems/active_admin-96c6db140e57/lib/active_admin/views/components/table_for.rb:120)```

This was previously reported in #3487 (fixed c8e54d2) and then amended in a way that reintroduced the deprecation warning (48ccc3db). 

That last commit provides justification for a why the method should be used. The problem remains, however, that anybody using Active Admin will deal with the noise of the deprecation warning. 

Rails provides a way to silence deprecation warnings on a particular section of code when you've decided you know better. Now is the time to use it.

**Comment by rdj** [comment]
Ok, since the PR has been closed, can we review what to actually do here? The commit history I outlined here shows that the aa team seems to have considered and rejected actually taking action to remove the deprecated action. While I agree that silencing deprecation warnings is a bad idea in general, I think that as a library you expect other people to use in their own rails apps, ignoring the deprecation warnings is even worse. As a library, deciding this actively determining to waste uncountable people's time in the future, as each and every rails app that uses active admin investigates this deprecation warning, deal with their own internal policies about how their apps are not allowed to have deprecation warnings, and has to decide whether to drop activeadmin or create a private fork that silences it, etc. 

So if we could revisit the previous commits here, can we agree that it would be preferable to have a fix that works correctly and does not emit the deprecation warning? 

@gonzedge - you contributed 48ccc3d — I have read the commit message, but I don't completely follow it. Possibly multiple rails versions are involved here, but you didn't specify.

Also, I get tons of failures on my MacBook running 10.10.2 when I try to run the test suite. I see Travis says the build is good? I looked at the contribution guidelines and it doesn't make it sound like running the tests is that hard; should I be able to get them working on my machine or do they only run on Linux or some other caveat I didn't see?

**Comment by rdj** [comment]
Oh, yeah, pull in @timoschilling since he closed the PR. Really would like to figure out something positive to do here rather than just ignoring the problem.

**Comment by seanlinsley** [comment]
@rdj what sort of test failures are you getting locally? Perhaps we could jump on IRC to try and figure what's happening together.

**Comment by timoschilling** [comment]
@rdj I agree with you too. Ignoring is not a solution. Hope you find a better way

**Comment by rdj** [comment]
@seanlinsley Thanks, here's what I'm currently seeing.

```$ git ls-remote . refs/heads/master
60914c887942cb34d737428fb9813f69bb8ae3ee        refs/heads/master```

I start with a completely blank slate in an isolated empty rvm gemset.

I run `bundle install`, which looks like it installs Rails 3.2.21. Here's the gemfile.lock: https://gist.github.com/rdj/8158b2563eadc5a578ec

I run `bundle exec rake test` and here's where things fail. Here's the output: https://gist.github.com/rdj/beb89f608c85efd95ee4

Seems like the `rake test` is trying to run the rails command line to create a rails app and stuff is failing.

Ok, so poking around I see that I can drop a .rails-version file to control what rails version I'm using, plus there's a script/use_rails for hotswitching between. So I decide I'll try rails 4.2.1.rc3 since that's what I'm trying to work fix problems with. I'll clean everything back out first though.

```rm -rf Gemfile.lock coverage spec/rails
rvm gemset empty
script/use_rails 4.2.1.rc3```

Here's the Gemfile.lock for that: https://gist.github.com/rdj/786a8667a523088c0f2e

Then when I run `bundle exec rake test` I get 71 failures. Here's the output: https://gist.github.com/rdj/1765492f84b684bccaf2

**Comment by rdj** [comment]
Double checked everything and get the same results. I also tried Rails 4.2 just for completeness and got a different type of failure: https://gist.github.com/rdj/5e7ee9c5b88f3a0197eb

**Comment by rdj** [comment]
Spun up a clean Ubuntu Trusty machine on EC2 and I get the same results, so I guess at least it's not Mac specific. (Though on linux I had to manually add therubyracer to the Gemfile.)

**Comment by timoschilling** [comment]
@rdj any updates?

**Comment by rdj** [comment]
@timoschilling I was never able to get tests running, so I'm in no position to prepare a fix.

In my app, these deprecations where coming up where an auto-formatted column (`column(:foo)`) was used with a highly tweaked scoped_collection with a group by and some aggregate function columns. When I replaced it with a manual column (`column(:foo) { |r| r.foo }`) I stopped getting the deprecations. This could be a good clue as to how to reproduce the problem.

I see now that the IRC channel is specified in the README.md, which I had missed at the time. I'm working on a different project at the moment, but perhaps I will have some time in the next couple of weeks to pop in. Like I said, I'd be happy to investigate if I can get the tests running.

**Comment by Fivell** [comment]
@timoschilling , why we need ```is_boolean?``` method at all?
https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/views/components/table_for.rb#L113

Why not to check if value is boolean  and not to check column type and so on?  something like

```[true, false].include? value```

What do you think?

**Comment by timoschilling** [comment]
What's about nil?

**Comment by Fivell** [comment]
@timoschilling, I'm  looking at tests and looks like it was decided to render nil as "No" for boolean columns , is that true ?  Can we change this or no ?

**Comment by seanlinsley** [comment]
@Fivell yes, `nil` should be rendered as "No". 

It wasn't well documented on the original Rails pull request, but in our case we should update our code to use [`type_for_attribute`](http://apidock.com/rails/v4.2.1/ActiveRecord/ModelSchema/ClassMethods/type_for_attribute) if it's defined (4.2 and above), else use `column_for_attribute`.

**Comment by seanlinsley** [comment]
Wait, this was already done in #3487, but then it later got reverted by #3730?

The reasoning for that change was:
> The `#is_boolean?` implementation calls `#type_for_attribute` or `#column_for_attribute` depending on the Rails version. However, `#type_for_attribute` returns an instance of `ActiveRecord::Type::Value` with a null `#type`, which makes the `#status_tag` tests fail.

They didn't go into detail how exactly the `status_tag` test fails, but that test (or the logic causing the failure) should be changed to handle a `ActiveRecord::Type::Value` that returns a `nil` type.

**Comment by seanlinsley** [comment]
CC @gonzedge

**Comment by Fivell** [comment]
@seanlinsley, let me describe "problematic" example.
#column_for_attribute(data) is raising deprecation warning in case there is no db column for attribute, there were few issues about this.
However in case if virtual columns like https://github.com/activeadmin/activeadmin/blob/6bde1f57ec5f9b724c21e5af146678f4ade839bc/features/index/index_as_table.feature#L270 
calling  ```#column_for_attribute``` will be always nil , which will give deprecation warning for rails 4.2.

**Comment by Fivell** [comment]
>>which makes the #status_tag tests fail. 

@gonzedge, can you tell what exact tests are failing?

**Comment by gonzedge** [comment]
I'm taking a look at the commit right before my pull request. I'll be back soon with the test failures.

**Comment by gonzedge** [comment]
**Below are my results on ruby `2.2.2`. I'll try running the same with ruby `2.2.0` later, since that was the version I was using at the time of the pull request. I will let you know what I find. I hope this helps the discussion.**

The commit `38bf0239a3f1eba20454748c9b1247200d7d52b3` was right before my pull request (#3730).

``` sh
git checkout 38bf023
```

Once you checkout that commit, you'll have to change the `Gemfile` to use the specific commit used at the time for `inherited_resources`, since the `rails-4-2` branch no longer exists. Replace the `inherited_resources` entry in the `Gemfile` with:

``` ruby
gem 'inherited_resources', github: 'josevalim/inherited_resources', ref: '9f1c0edd6b4c'
```

Then, bundle and test (which will fail in the unit tests):

``` sh
rm Gemfile.lock
RAILS=4.2.0 bundle
RAILS=4.2.0 bundle exec rake test
```

These are the unit test failures I'm getting. The important ones here are 1 and 5 on `spec/unit/filters/filter_form_builder_spec.rb:297` and `spec/unit/views/components/table_for_spec.rb:278`, but for some reason I'm getting failures 2, 3 & 4. Interestingly, 2, 3 & 4 are also failing on the pull request commits, so let's not pay attention to them for now:

```
  1) ActiveAdmin::Filters::ViewHelper belongs_to when using a custom foreign key should should ignore that foreign key and let Ransack handle it
     Failure/Error: expect(Post.reflections[:category].foreign_key).to eq :custom_category_id
     NoMethodError:
       undefined method `foreign_key' for nil:NilClass
     # ./spec/unit/filters/filter_form_builder_spec.rb:297:in `block (4 levels) in <top (required)>'

  2) ActiveAdmin::FormBuilder with has many inputs with allow destroy with an existing post should include a boolean field for _destroy
     Failure/Error: allow(f.object.posts.build).to receive(:new_record?).and_return(false)
     NoMethodError:
       undefined method `allow' for #<ActiveAdmin::Views::ActiveAdminForm:0x007f8ac80d71e0>
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/element.rb:182:in `method_missing'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/rails/forms.rb:37:in `method_missing'
     # ./spec/unit/form_builder_spec.rb:493:in `block (6 levels) in <top (required)>'
     # ./lib/active_admin/views/components/active_admin_form.rb:35:in `instance_eval'
     # ./lib/active_admin/views/components/active_admin_form.rb:35:in `build'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:28:in `block in build_tag'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/context.rb:92:in `with_current_arbre_element'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:26:in `build_tag'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:14:in `active_admin_form_for'
     # ./spec/unit/form_builder_spec.rb:37:in `block in build_form'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/context.rb:45:in `instance_eval'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/context.rb:45:in `initialize'
     # ./spec/rails_helper.rb:53:in `new'
     # ./spec/rails_helper.rb:53:in `arbre'
     # ./spec/rails_helper.rb:57:in `render_arbre_component'
     # ./spec/unit/form_builder_spec.rb:36:in `build_form'
     # ./spec/unit/form_builder_spec.rb:492:in `block (5 levels) in <top (required)>'
     # ./spec/unit/form_builder_spec.rb:501:in `block (5 levels) in <top (required)>'

  3) ActiveAdmin::FormBuilder with has many inputs with allow destroy with an existing post should have a check box with 'Remove' as its label
     Failure/Error: allow(f.object.posts.build).to receive(:new_record?).and_return(false)
     NoMethodError:
       undefined method `allow' for #<ActiveAdmin::Views::ActiveAdminForm:0x007f8ac80ea2e0>
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/element.rb:182:in `method_missing'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/rails/forms.rb:37:in `method_missing'
     # ./spec/unit/form_builder_spec.rb:493:in `block (6 levels) in <top (required)>'
     # ./lib/active_admin/views/components/active_admin_form.rb:35:in `instance_eval'
     # ./lib/active_admin/views/components/active_admin_form.rb:35:in `build'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:28:in `block in build_tag'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/context.rb:92:in `with_current_arbre_element'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:26:in `build_tag'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:14:in `active_admin_form_for'
     # ./spec/unit/form_builder_spec.rb:37:in `block in build_form'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/context.rb:45:in `instance_eval'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/context.rb:45:in `initialize'
     # ./spec/rails_helper.rb:53:in `new'
     # ./spec/rails_helper.rb:53:in `arbre'
     # ./spec/rails_helper.rb:57:in `render_arbre_component'
     # ./spec/unit/form_builder_spec.rb:36:in `build_form'
     # ./spec/unit/form_builder_spec.rb:492:in `block (5 levels) in <top (required)>'
     # ./spec/unit/form_builder_spec.rb:505:in `block (5 levels) in <top (required)>'

  4) ActiveAdmin::FormBuilder with has many inputs with allow destroy with an existing post should wrap the destroy field in an li with class 'has_many_delete'
     Failure/Error: allow(f.object.posts.build).to receive(:new_record?).and_return(false)
     NoMethodError:
       undefined method `allow' for #<ActiveAdmin::Views::ActiveAdminForm:0x007f8ac6c5d3b8>
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/element.rb:182:in `method_missing'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/rails/forms.rb:37:in `method_missing'
     # ./spec/unit/form_builder_spec.rb:493:in `block (6 levels) in <top (required)>'
     # ./lib/active_admin/views/components/active_admin_form.rb:35:in `instance_eval'
     # ./lib/active_admin/views/components/active_admin_form.rb:35:in `build'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:28:in `block in build_tag'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/context.rb:92:in `with_current_arbre_element'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:26:in `build_tag'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:14:in `active_admin_form_for'
     # ./spec/unit/form_builder_spec.rb:37:in `block in build_form'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/context.rb:45:in `instance_eval'
     # ~/.rvm/gems/ruby-2.2.2@activeadmin/gems/arbre-1.0.3/lib/arbre/context.rb:45:in `initialize'
     # ./spec/rails_helper.rb:53:in `new'
     # ./spec/rails_helper.rb:53:in `arbre'
     # ./spec/rails_helper.rb:57:in `render_arbre_component'
     # ./spec/unit/form_builder_spec.rb:36:in `build_form'
     # ./spec/unit/form_builder_spec.rb:492:in `block (5 levels) in <top (required)>'
     # ./spec/unit/form_builder_spec.rb:509:in `block (5 levels) in <top (required)>'

  5) ActiveAdmin::Views::TableFor creating with the dsl when record attribute is boolean should render boolean attribute within status tag
     Failure/Error: expect(table.find_by_tag("span").first.class_list.to_a.join(' ')).to eq "status_tag yes"
     NoMethodError:
       undefined method `class_list' for nil:NilClass
     # ./spec/unit/views/components/table_for_spec.rb:278:in `block (4 levels) in <top (required)>'
```

From `rake cucumber`, the important failure happens in `features/index/index_as_table.feature:244`. For some reason, I'm also getting a new failure I wasn't getting before (`features/index/filters.feature:109`), but it's also failing in the pull request commits, so let's ignore it for now as well:

```
(::) failed steps (::)

One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

ReferenceError: Can't find variable: options
ReferenceError: Can't find variable: options
    at http://127.0.0.1:53633/assets/active_admin.js:20350 in CheckboxToggler
    at http://127.0.0.1:53633/assets/active_admin.js:20794 in TableCheckboxToggler
    at http://127.0.0.1:53633/assets/active_admin.js:12966
    at http://127.0.0.1:53633/assets/active_admin.js:385
    at http://127.0.0.1:53633/assets/active_admin.js:137
    at http://127.0.0.1:53633/assets/active_admin.js:12968
    at http://127.0.0.1:53633/assets/active_admin.js:20324
    at http://127.0.0.1:53633/assets/active_admin.js:3144
    at http://127.0.0.1:53633/assets/active_admin.js:3256
    at http://127.0.0.1:53633/assets/active_admin.js:3468
    at http://127.0.0.1:53633/assets/active_admin.js:3499 in completed (Capybara::Poltergeist::JavascriptError)
./features/step_definitions/web_steps.rb:23:in `/^(?:I )am on (.+)$/'
./features/step_definitions/configuration_steps.rb:65:in `/^a(?:n? (index|show))? configuration of:$/'
features/index/filters.feature:113:in `And an index configuration of:'


expected: "No"
     got: ""

(compared using ==)
 (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/table_steps.rb:96:in `assert_cells_match'
./features/step_definitions/table_steps.rb:79:in `block (2 levels) in assert_tables_match'
./features/step_definitions/table_steps.rb:75:in `each_index'
./features/step_definitions/table_steps.rb:75:in `block in assert_tables_match'
./features/step_definitions/table_steps.rb:74:in `each_index'
./features/step_definitions/table_steps.rb:74:in `assert_tables_match'
./features/step_definitions/table_steps.rb:115:in `/^I should see the "([^"]*)" table:$/'
features/index/index_as_table.feature:252:in `Then I should see the "index_table_posts" table:'

Failing Scenarios:
cucumber features/index/filters.feature:109 # Scenario: Clearing filter preserves custom parameters
cucumber features/index/index_as_table.feature:244 # Scenario: Sorting
```

Notice the `expected: "No" got: ""` failure above.

For `rake spec:integration` and `rake cucumber:class_reloading`, I get no failures.

After updating to commit e7dafc53739c228cc2df54dac6e8e9b4ba4115a4, I don't get the highlighted failures anymore (
`spec/unit/filters/filter_form_builder_spec.rb:297` and `spec/unit/views/components/table_for_spec.rb:278` for `rake spec:unit` and `features/index/index_as_table.feature:244` for `rake cucumber`).
