### ISSUE TITLE
Add search status panel name in I18n

### ISSUE THREAD

**Issue by marcomd** [activeadmin/activeadmin#4230]
Hi guys,
I would add the filter panel name:

```yaml
    search_status:
	  search_status_name: "Search status:"
```
/lib/active_admin/filters/resource_extension.rb

```ruby
  # row 132
  ActiveAdmin::SidebarSection.new I18n.t("active_admin.search_status.search_status_name", :default => 'Search status'), only: :index, if: -> { params[:q] || params[:scope] } do
```
I also added the new tag in the config/locale yml file for :en and :it

**Comment by timoschilling** [comment]
name it `"active_admin.search_status.headline"` and remove the default.

**Comment by marcomd** [comment]
There is already headline, could i name it "headname" ?

```yaml
    search_status:
      headname: "Search status:"
      headline: "Scope:"
      current_filters: "Current filters:"
      no_current_filters: "None"
```
