### ISSUE TITLE
formtastic i18n not working for titles?

### ISSUE THREAD

**Issue by niksfirefly** [activeadmin/activeadmin#4285]
After reading:
https://github.com/justinfrench/formtastic#enhanced-localization-formtastic-i18n-api
I'm trying to set up i18n for titles in forms
for example translate
```
f.inputs :model_title
```
with .yml
```
formtastic:
  titles:
    model_title: "translated title"
```

Beside titles everything works in AA like expected

**Comment by timoschilling** [comment]
you need a I18n local as root key
```yaml
en:
  formtastic:
    titles:
      model_title: "translated title"
```
