### ISSUE TITLE
Meet a strange problems

### ISSUE THREAD

**Issue by w-zengtao** [activeadmin/activeadmin#4732]
![wechatimg37](https://cloud.githubusercontent.com/assets/5390765/22010139/63f4715e-dcc2-11e6-9d2e-9b31e4fae3fc.jpeg)

**Comment by timoschilling** [comment]
please provide more context

**Comment by Fivell** [comment]
@timoschilling , I think related to formtastic. 
https://github.com/justinfrench/formtastic/blob/ec0b090de764f09cd7d68177ac6fea9011d907b4/lib/formtastic/inputs/base/timeish.rb

@w-zengtao , check if it helps when adding strings to locale
```

en:
  date:
    month_names: [~, January, February, March, April, May, June, July, August, September, October, November, December]
    abbr_month_names: [~, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]

```
