### ISSUE TITLE
RSpec failing controller test due to constant loading bug in docker-compose on google cloud-build.

### ISSUE THREAD

**Issue by christopherdbull** [activeadmin/activeadmin#5795]
[Please follow the guidelines for creating a bug report](https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md#4-did-you-find-a-bug).

The issue tracker is only for bugs and feature requests. If you need general
help please post to
[StackOverflow](http://stackoverflow.com/questions/tagged/activeadmin).

### Expected behavior

RSpec should run my test in google cloud build docker compose environment. Have enabled the following in my test.rb env

```
config.eager_load = true
config.enable_dependency_loading = true
```

### Actual behavior

Rspec crashes with:
```
An error occurred while loading ./spec/controllers/referrer_options_controller_spec.rb.
Failure/Error:
  RSpec.describe Admin::ReferrerOptionsController, type: :controller do
  
    render_views
  
    let(:page) { Capybara::Node::Simple.new(response.body) }
    let(:user) { create(:admin_user) }
    before { sign_in user }
  
    let!(:referrer_option) { create(:referrer_option) }
  

NameError:
  uninitialized constant Admin::ReferrerOptionsController
# /usr/local/bundle/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant'
# /usr/local/bundle/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
# /usr/local/bundle/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `rescue in load_missing_constant'
# /usr/local/bundle/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `load_missing_constant'
# ./spec/controllers/referrer_options_controller_spec.rb:5:in `<top (required)>'
# /usr/local/bundle/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
# /usr/local/bundle/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
# ------------------
# --- Caused by: ---
# NameError:
#   uninitialized constant Admin::ReferrerOptionsController
#   /usr/local/bundle/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant'

```

If I remove the ActiveAdmin controller spec then my suite runs. This is the only file causing issues, I assume somewhere due to the meta programming being performed by AA.
### How to reproduce

Create a project with a resource. Add a controller test. Setup with docker-compose using the following:

```
ActiveAdmin.register ReferrerOption do
  menu parent: 'CMS'

  actions :all

  index do
    selectable_column
    column :value do |referrer_option|
      link_to referrer_option.value, admin_referrer_option_path(referrer_option)
    end
    actions defaults: true
  end

  form do |f|
    f.inputs 'Details' do
      f.input :value
    end
    f.actions
  end

  controller do
    def permitted_params
      params.permit!
    end
  end
end

```

Dockerfile:
```
# Install ruby on linux
FROM ruby:2.5.1

# Install utilities
RUN curl -sL https://deb.nodesource.com/setup_11.x | bash - && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && \
    apt-get install -qq -y \
    build-essential \
    postgresql-client \
    less \
    git \
    nodejs \
    yarn \
    imagemagick \
    tzdata

# Create and makes working directory app
WORKDIR /app

# Add directory for renderer project
RUN mkdir renderer

# Copy all gemfile to allow caching
COPY Gemfile Gemfile.lock .ruby-version ./

# Install all gems
RUN bundle install
```

docker-compose.yml:
```
version: '3.7'
services:
  db:
    container_name: db
    image: postgres:10
    volumes:
      - rails_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - proxynet
  redis:
    container_name: redis
    image: redis:5-alpine
    ports:
      - "6379:6379"
    networks:
      - proxynet
  web:
    container_name: web
    tty: true
    stdin_open: true
    build:
      context: .
    volumes:
      - .:/app:delegated
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - proxynet

volumes:
  rails_pgdata:

networks:
  proxynet:
    name: dev-network
```
Deploy to cloudbuild with:
```
steps:
- name: 'gcr.io/{$PROJECT}/docker-compose'
  args: ['run', 'web', 'bash', './test.sh']
```
