### ISSUE TITLE
How to render nested forms as table?

### ISSUE THREAD

**Issue by sigmaray** [activeadmin/activeadmin#5857]
Hi. I'm unable to render nested forms as table.

I wrote this code:  
```css
/* active_admin.scss */

.form-table {
  margin: 0 10px;
  width: calc(100% - 20px)
}
.form-table__row:nth-child(even) {
  background: #fff;
}
.form-table__row:nth-child(odd) {
  background: #e8e8e8;
}
.form-table__col {
  text-align: center;
  vertical-align: middle;
}
th.form-table__col {
  background-color: #efefef;
  background-image: linear-gradient(180deg, #efefef, #dfe1e2);
  text-shadow: #fff 0 1px 0;
  border: solid 1px #cdcdcd;
  border-color: #d4d4d4;
  border-top-color: #e6e6e6;
  border-right-color: #d4d4d4;
  border-bottom-color: #cdcdcd;
  border-left-color: #d4d4d4;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 0 1px #FFF inset;
  font-size: 1em;
  font-weight: bold;
  line-height: 18px;
  margin-bottom: 0.5em;
  color: #5E6469;
  padding: 5px 10px 3px 10px;
  border-right: none;
  padding-left: 12px;
  padding-right: 12px;
}
td.form-table__col {
  padding: 10px 0;
}
```
```ruby
inputs 'Rates' do
  table(class: 'form-table') do
    tr do
      th 'Currency', class: 'form-table__col'
      th 'Term', class: 'form-table__col'
      th 'Rate', class: 'form-table__col'
      th 'Destroy', class: 'form-table__col'
    end
    f.semantic_fields_for :rates, f.object.rates.with_ordered_currencies do |r|
      tr(class: 'form-table__row') do
        td(class: 'form-table__col') do
          r.input :currency_code,
                  label: false,
                  collection: options_for_select(
                    Currency::CURRENCY_CODES,
                    r.object.currency.try(:currency_code)
                  )
        end
        td(class: 'form-table__col') do
          r.input :term, label: false
        end
        td(class: 'form-table__col') do
          r.input :rate, label: false
        end
        td(class: 'form-table__col') do
          r.input :id, as: :hidden, label: ''
          r.input :_destroy, as: :boolean, label: ''
        end
      end
    end
  end
end
```
And got this UI:

![image](https://user-images.githubusercontent.com/1594701/64872997-e3dab600-d650-11e9-84bb-a8432314f3a8.png)

(there are redundant inputs above table)

Then I wrote weird and ugly monkey patches:
```ruby
# config/initializers/active_admin_patches.rb

# rubocop:disable all

# https://github.com/justinfrench/formtastic/issues/712#issuecomment-419869316
# Adding `wrapper_html: { tag: ... }` option. Value can be :td, :div, :any_html_tag
# or false (if you don't need wrapper tag)
module Formtastic
  module Inputs
    module Base
      module Wrapping
        def input_wrapping(&block)
          tag = options.fetch(:wrapper_html, {}).delete(:tag)
          content = [template.capture(&block), error_html, hint_html].join("\n").html_safe
          if tag != false
            tag ||= 'li'
            template.content_tag(tag, content, wrapper_html_options)
          else
            content
          end
        end
      end
    end
  end
end

# Adding `wrapper_tag  option. Value can be :td, :div, :any_html_tag
module ActiveAdmin
  module Views
    class SemanticInputsProxy < FormtasticProxy
      def build(form_builder, *args, &block)
        html_options = args.extract_options!
        html_options[:class] ||= "inputs"
        legend = args.shift if args.first.is_a?(::String)
        legend = html_options.delete(:name) if html_options.key?(:name)
        legend_tag = legend ? "<legend><span>#{legend}</span></legend>" : ""

        # fieldset_attrs = html_options.map { |k, v| %Q{#{k}="#{v}"} }.join(" ")
        # @opening_tag = "<fieldset #{fieldset_attrs}>#{legend_tag}<ol>"
        # @closing_tag = "</ol></fieldset>"
        wrapper_tag = html_options.delete(:wrapper_tag)
        fieldset_attrs = html_options.map { |k, v| %Q{#{k}="#{v}"} }.join(" ")
        if wrapper_tag.blank?
          @opening_tag = "<fieldset #{fieldset_attrs}>#{legend_tag}<ol>"
          @closing_tag = "</ol></fieldset>"
        else
          @opening_tag = "<#{wrapper_tag} #{fieldset_attrs}>"
          @closing_tag = "</#{wrapper_tag} #{fieldset_attrs}>"
        end

        super(*(args << html_options), &block)
      end
    end
  end
end

# rubocop:enable all
```
```ruby
inputs 'Rates' do
  table(class: 'form-table') do
    tr do
      th 'Currency', class: 'form-table__col'
      th 'Term', class: 'form-table__col'
      th 'Rate', class: 'form-table__col'
      th 'Destroy', class: 'form-table__col'
    end
    f.semantic_fields_for :rates, f.object.rates.with_ordered_currencies do |r|
      f.inputs wrapper_tag: :tr, class: 'form-table__row' do
        f.inputs wrapper_tag: :td, width: 300, class: 'form-table__col' do
          r.input :currency_code,
                  label: false,
                  wrapper_html: { tag: false },
                  collection: options_for_select(
                    Currency::CURRENCY_CODES,
                    r.object.currency.try(:currency_code)
                  )
        end

        f.inputs wrapper_tag: :td, class: 'form-table__col' do
          r.input(:term, label: false, wrapper_html: { tag: false })
        end

        f.inputs wrapper_tag: :td, class: 'form-table__col' do
          r.input(:rate, as: :string, label: false, wrapper_html: { tag: false })
        end

        f.inputs wrapper_tag: :td, width: 150, class: 'form-table__col' do
          r.input :id, as: :hidden, label: '', wrapper_html: { tag: false }
          r.input :_destroy, as: :boolean, label: '', wrapper_html: { tag: false }
        end
      end
    end
  end
end
```
Now it looks fine:
![image](https://user-images.githubusercontent.com/1594701/64873307-724f3780-d651-11e9-9006-c827f32ff8eb.png)

The problem is that my patches look terrible. Is there a better way to render table form?

I'm using:
ruby '2.5.1'
rails (5.2.3)
activeadmin (2.2.0)
formtastic (3.1.5)

Thanks.
