### ISSUE TITLE
Weird translation in breadcrumbs

### ISSUE THREAD

**Issue by nooga** [activeadmin/activeadmin#629]
![WTF](http://img406.imageshack.us/img406/8767/weirdd.png)

While having:

``` yaml
  activerecord:
    models:
      user: 
        one: "Użytkownik"
        few: "Użytkownicy"
        other: "Użytkownicy"
```

in active locale.
