### ISSUE TITLE
`resource_name` does not use the host app's translation

### ISSUE THREAD

**Issue by ahx** [activeadmin/activeadmin#820]
If you put this in config/locales/en.yml (in the test-rails-app that's generated by ./script/local server),

``` yml
en:
  hello: "Hello world"
  activerecord:
    models:
      category:
        one: Denomination
        other: Denominations
```

then start the app with ./script/local server
and open http://localhost:3000/admin/categories/5/edit
you get this: ![denominations mixed with categories](http://p.twimg.com/AgBmds5CQAAUoMJ.png)

If you open a console you get:

``` irb
ruby-1.9.2-p290 :001 > Category.model_name.human
 => "Denomination" 
```

Running AA edge (3c4ac594f5571e6792d1834cf54f973c7da9107b)
(this happen with both Rails 3.1.0 and 3.1.3)
