### ISSUE TITLE
Tailwind `plugin.js` is not compatible with Tailwind 4

### ISSUE THREAD

**Issue by henrikbjorn** [activeadmin/activeadmin#8615]
Describe your issue with a **clear title and description**. Make sure to include as much relevant information as possible, including a code sample or failing test that demonstrates the expected behavior, as well as your system configuration. Your goal should be to make it easy for yourself - and others - to reproduce the bug and figure out a fix.

### Expected behavior

Tailwind 4 goes a long way of having BC with earlier versions. But the `plugin.js` is using some invalid utility types and there for isn't compatible with it.

### Actual behavior

Should work with Tailwind 4 through the `@plugin` directlive or their js config bc layer

### How to reproduce

Install ActiveAdmin and use Tailwind 4

**Comment by tagliala** [comment]
Hello,

this is a feature request to migrate to Tailwind 4

**Comment by henrikbjorn** [comment]
``` css
@import "tailwindcss" source(none);

@plugin "@activeadmin/activeadmin/plugin";

@source "/bundle/ruby/3.4.0/gems/activeadmin-4.0.0.beta15/app/views/**/*.{arb,erb,html,rb}";
@source "/bundle/ruby/3.4.0/gems/activeadmin-4.0.0.beta15/plugin.js";
@source "/app/node_modules/flowbite/plugin.js";

@source "../../admin/**/*.rb";
@source "../../views/active_admin/**/*.{arb,erb,html,rb}";
@source "../../views/admin/**/*.{arb,erb,html,rb}";

@custom-variant dark (&:where(.dark, .dark *));

@utility ring-opacity-5 {
  --tw-ring-opacity: 0.05;
}

@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--color-gray-200, currentColor);
  }
}
```

This works for Tailwind 4
